### ISSUE TITLE
Investigate: Move load balancer from one k8s cluster to another

### ISSUE THREAD

**Issue by lxfontes** [digitalocean/digitalocean-cloud-controller-manager#130]
From kubernetes docs:
https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

> Some cloud providers allow the loadBalancerIP to be specified. In those cases, the load-balancer will be created with the user-specified loadBalancerIP. If the loadBalancerIP field is not specified, an ephemeral IP will be assigned to the loadBalancer. If the loadBalancerIP is specified, but the cloud provider does not support the feature, the field will be ignored.

Ran a quick test and we are not respecting `loadBalancerIP`.

**Comment by goenning** [comment]
Agreed, it's not, it always creates a new LB. Having the option to assign a Floating IP to a LB would be handy too!

**Comment by timoreimann** [comment]
We introduced a new annotation some time ago that specifies the LB ID a service is associated with. While the primary purpose is to ensure LBs do not "get lost", it can also be used to start owning an existing LB. You just have to make sure that any previously owning clusters do not exist anymore (to prevent two service objects fighting over the same LB). See [the docs](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/64d376729fbf81e72a4ddc5200acd285d815ea87/docs/getting-started.md#load-balancer-id-annotations) for details.

For the case where clusters are being upgraded, LBs should be moved over seamlessly now that minor version upgrades are supported.

For people who do not find their use case covered by any of the two: please comment or file a new issue so that we can think of additional ways.
