### ISSUE TITLE
Add label according to node's pool

### ISSUE THREAD

**Issue by wnagele** [digitalocean/digitalocean-cloud-controller-manager#136]
Currently node's do not have a label that shows which pool they are part of. It would be helpful to have this information in order to schedule resources better.

**Comment by andrewsykim** [comment]
Hey @wnagele, we don't add labels per node pool, but we do have lables for droplet _size_ (see [here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/node/labels.md#betakubernetesioinstance-type)). Would that still accomplish what you need?

**Comment by wnagele** [comment]
I envision a case of scaling a cluster up and down to cater for base VS peak load. In this case it seems like a good idea to use different node pools to do so. It would allow to pin resources that have to run to ensure base functionality to a specific node pool. A generic transpose of tags as suggested in #135 into labels would also work as we could tag the droplets accordingly.

**Comment by mattkelly** [comment]
@wnagele thanks for opening this! We're interested in this exact use case for integrating the Cerebral autoscaler - see this related issue: https://github.com/containership/cerebral/issues/52. This is the only thing blocking us from having a fully functional autoscaling integration on DO Kubernetes.

@andrewsykim I did notice that #142 is ready (?) but sitting around going stale. Are you able to provide any insight on an ETA for this going in? Thanks!

**Comment by andrewsykim** [comment]
Hi @mattkelly! We're currently discussing what the best label format should be as it will be difficult to change once it's deployed. Please let me know if you have any opinions on this, right now it's `digitalocean.com/droplet-tag/<tag>`. cc @joonas

**Comment by normanjoyner** [comment]
So this is a bit tricky in my opinion. Labels in Kubernetes have more strict, and generally different, validation than do tags in DigitalOcean. For instance, by default DigitalOcean Kubernetes node pools are tagged with `k8s:${cluster_id}`. This tag would be invalid in Kubernetes since colons are not allowed in the neither the label key, nor the value. Ignoring validation, in my opinion it would be nice if instead of this creating a `digitalocean.com/droplet-tag/k8s:${cluster_id}=""` label, it created `digitalocean.com/droplet-tag/k8s=${cluster_id}` (ignoring the fact that label key should really be more explicitly named such as `digitalocean.com/droplet-tag/cluster-id=${cluster_id}`). Not being able to achieve setting a value on labels feels like we're nerfing the power of Kubernetes.

I'm sure others have better ideas around this, but one naïve approach to achieve this functionality could be to treat the colon as an equals, thus pseudo-creating key-value pairs. This of course is limited by the fact that tags in DigitalOcean can have multiple colons, so it would need to be well documented that those tags would never be synced. If DigitalOcean could support explicit key-value pairs delimited by an equals sign, that would serve as the easiest fix :)

**Comment by andrewsykim** [comment]
Good catch on the label validation @normanjoyner

**Comment by timoreimann** [comment]
Going through the various requests received, what seems to be the primary use case expressed by most users is the ability to select node pools and subsequently apply certain actions on them, such as scaling or scheduling. This could already be accomplished by setting node pool identifiers as labels on the affected nodes (which has also been mentioned by @normanjoyner).

Support for a way to apply (and persist) arbitrary labels to DOKS-managed nodes is still on the radar; as others have pointed out as well, however, translating tags to labels isn't straight-forward and comes with certain limitations. That's why we want to spend more time thinking about a more flexible labeling mechanism (where one possibility could be to expose a label interface directly instead of going through DO tags) and focus on node pool identifiers first to serve the immediate needs.

Let me know what your thoughts are on the proposed path forward.

**Comment by normanjoyner** [comment]
To me, this seems like a reasonable path forward. I would love to see the node pool ID as the label value, as opposed to part of the key with an empty value. The same goes for cluster ID (as outlined in my comment above).

**Comment by timoreimann** [comment]
Thanks for your feedback, @normanjoyner. I think canonical label values is what we are aiming for now.

Can I ask what you'd like to use the cluster ID for if it were attached as a label (ideally in proper key/value form)? I presume this is for discovery purposes which the DO API should also allow hopefully? Just trying to understand use cases better so that we can account for it. Thanks!

**Comment by normanjoyner** [comment]
From the perspective of a Kubernetes application developer, the more “metadata” exposed through labels, the better. With well-defined labels such as `digitalocean.com/cluster-id` (as an example), I can rely on the label value to make API calls to the DigitalOcean API that affect the cluster my application is running on, without additional configuration from my end-user. Ultimately this makes my application more portable between DOKS clusters. Furthermore, when thinking about running and managing multiple DOKS clusters, I am able to rely on this label for more advanced scheduling and placement techniques.

**Comment by timoreimann** [comment]
@normanjoyner thanks for elaborating, that does make a lot of sense. I have created an internal ticket to track progress on this one.

**Comment by normanjoyner** [comment]
For those interested, I noticed DOKS node pools now have the `doks.digitalocean.com/node-pool-id` label, with corresonding node pool UUID value. Note: this does not yet include support for arbitrary tag syncing. Thanks @timoreimann!

**Comment by timoreimann** [comment]
Thanks for sharing the news @normanjoyner, I missed to post an update to this issue.

**Comment by timoreimann** [comment]
@boedy apologies for the inconveniences this has caused; unfortunately, we have no news to share yet as to when we will be able to provide better support for labels (and taints).

The best advice I can give for now is to create a custom controller that reconciles labels/taints based on node pool labels. I know it's not ideal but might be a workaround for you and others.

**Comment by normanjoyner** [comment]
I think the original issue opened by @wnagele is satisfied by the addition of the `doks.digitalocean.com/node-pool-id` label. Related issues, such as the syncing of arbitrary DigitalOcean tags as labels, have been raised in this thread (and work was started in #142, which was subsequently closed with good reason). I’m happy to encapsulate these points into a new issue to track moving forward if we feel this issue can be closed out. I think this is functionality that the wider DigitalOcean Kubernetes community will be interested in moving forward, so ensuring there is a public place to track updates and gather feedback would be encouraged from my point of view.  @timoreimann @andrewsykim

**Comment by timoreimann** [comment]
@normanjoyner sorry for the delay. I agree that the feature request raised by this issue has been implemented, so we can close it.

The way it stands right now, CCM will likely not be involved in the implementation of a generic system to accept and persist user-provided labels as it makes more sense to build a dedicated component for it. And such, I am somewhat hesitant to track any progress in this repository which could create false expectations (the predominant one that CCM is the component users would have to wait for or could try to contribute to it in order to implement the feature).

I do understand the value in having a two-way communication channel though. For this purpose, DO runs https://ideas.digitalocean.com/ to accept ideas / feature requests and stay in touch with the community. Would you be fine with submitting a ticket / an idea over there and use it to solicit periodic updates / leave feedback?

Appreciate your and everybody else's feedback towards what we have built so far and what lies ahead. Thanks!

**Comment by timoreimann** [comment]
(Closing, but I'll continue to watch for post updates on this issue to wrap up the discussion.)

**Comment by normanjoyner** [comment]
Thanks for the update @timoreimann ... I’ve created [an idea](https://ideas.digitalocean.com/ideas/K8SX-I-8) for this if anyone else is interested in tracking / lending input.

**Comment by timoreimann** [comment]
Thank you @normanjoyner, appreciated.

**Comment by timoreimann** [comment]
We have a dedicated repository by now to track generic feature requests and bug reports for DOKS. Further updates and discussions will go through digitalocean/DOKS#3.
