### ISSUE TITLE
Missing toleration prevents controller manager from being scheduled on master

### ISSUE THREAD

**Issue by Ratedev** [digitalocean/digitalocean-cloud-controller-manager#139]
Kubernetes Version: 1.12.1
When setting --cloud-provider=external on the kubelet on the master node, the master gets the following taint: node.kubernetes.io/not-ready:NoSchedule

please add following tolaration to the controller manager:
 - key: "node.kubernetes.io/not-ready"
    effect: NoSchedule

**Comment by andrewsykim** [comment]
The node taint corresponding to `--cloud-provider=external` is actually `node.cloudprovider.kubernetes.io/uninitialized` (see [here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/releases/v0.1.8.yml#L25)). `node.kubernetes.io/not-ready` taint is usually due to some other issues on the node, does `kubectl describe node` say anything useful?

**Comment by Ratedev** [comment]
Ah, yes. Sorry.
It was weave-net that does not like the uninitialized state
