### ISSUE TITLE
DO CCM fails to boot up in fresh Kubernetes v1.14.1 install

### ISSUE THREAD

**Issue by peterver** [digitalocean/digitalocean-cloud-controller-manager#217]
I setup a fresh kubernetes v1.14.1 cluster today and applied the latest version (0.1.14) yaml for DO CCM.

However I feel there is a missing permission being requested here : 

```
W0516 20:53:27.721079       1 authentication.go:262] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

after adding `configmaps` to the resources of the cluster role with the following command, the issue appears to be fixed : 

```
kubectl create rolebinding -n kube-system configmaps --role=extension-apiserver-authentication-reader --serviceaccount=kube-system:cloud-controller-manager
```

@fatih @nanzhong was there something up with my local install or is there something missing here?

**Comment by timoreimann** [comment]
@peterver I have a hunch that this might be due to us having updated to the Kubernetes 1.14 dependencies with DO CCM 0.1.14: The updated cloud provider framework seems to pull in a fair amount of bootstrapping logic that should probably happen in kube-controller-manager only. (One concrete example  being kubernetes/kubernetes#76205.)

Specifically, the warning [originates from an authentication part of the vendored code](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/188293a4f7e7bd00f6124945dbbdd51a54adaaa4/vendor/k8s.io/apiserver/pkg/server/options/authentication.go#L262). A const comment around the ConfigMap that's supposed to be retrieved says this:

>	// authenticationConfigMapName is the name of ConfigMap in the kube-system namespace holding the root certificate
	// bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified
	// by --requestheader-username-headers. This is created in the cluster by the kube-apiserver.

However, CCM does not need to verify any clients; that's the job of the API server.

Could you try adding the `--authentication-skip-lookup=true` and see if it helps (without the RBAC changes you did)?

**Comment by peterver** [comment]
that does seem to do the trick @timoreimann

**Comment by timoreimann** [comment]
@peterver thanks for verifying. We can put the flag into our manifests until we know what a better long-term solution could look like.

**Comment by timoreimann** [comment]
@andrewsykim this issue looks like another case of the cloud provider framework pretending too much to be KCM in a CCM context. Would you share my thoughts? If so, is that something which is possibly tracked somewhere upstream already?

**Comment by andrewsykim** [comment]
I would put that under https://github.com/kubernetes/cloud-provider/issues/29. There were some efforts in v1.14 to make the various Kubernetes components more consistent (i.e. use the same set of libs for common things like flags) which likely caused this issue. I don't know the exact commit to look at yet but happy to dig into post KubeCON.

**Comment by timoreimann** [comment]
@andrewsykim sounds good, thanks!

**Comment by timoreimann** [comment]
PR 226 referenced above hard-coded the `--authentication-skip-lookup=true` flag into the binary (along with two other flags that always need to be set with a specific value; see [the change log](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/24bfc8d33187f9597d562d343bd7f1294fc8e824/CHANGELOG.md#unreleased)). So the next CCM release (which is intended to be cut relatively soon) is going to ship the fix.

**Comment by timoreimann** [comment]
[v0.1.15 has been released](https://github.com/digitalocean/digitalocean-cloud-controller-manager/releases/tag/v0.1.15).
