### ISSUE TITLE
Public/private IP addresses cannot be used as node names anymore

### ISSUE THREAD

**Issue by yamamoto-febc** [digitalocean/digitalocean-cloud-controller-manager#218]
(from: https://github.com/yamamoto-febc/terraform-provider-rke/pull/88#discussion_r286410875)

I tried ccm by specifying private IP as the node name with following options: 

- kube-apiserver: `--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname`
- kubelet: ` --cloud-provider=external`

However, ccm reported following error.

```sh
NodeAddress: Error fetching by providerID: providerID cannot be empty string Error fetching by NodeName: instance not found
```

I found in #56 that private or public IP was supported, but the current code seems to support only the droplet name.

- func `NodeAddress` calls to `resource.DropletByName`

https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/cloud-controller-manager/do/droplets.go#L52-L58

- `resource.DropletByName` finds droplet from `dropletNameMap`

https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/cloud-controller-manager/do/resources.go#L83-L89

- `dropletNameMap` is set from the following two places, but public/private IP is not used

https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/cloud-controller-manager/do/resources.go#L147
https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/cloud-controller-manager/do/resources.go#L210

### versions

- kubernetes: v1.13
- ccm: v0.1.13

**Comment by timoreimann** [comment]
Hey @yamamoto-febc,

thanks for filing the issue. Indeed, I believe we introduced a regression when we added the caching layer along #200. :(

One way to deal with this is to expand on the keys we support within [`SyncDroplet`](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/151e75b4f4ce04a025787a2e5d64d82c2e75a5b4/cloud-controller-manager/do/resources.go#L180) (and likely also [`UpdateDroplets`](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/151e75b4f4ce04a025787a2e5d64d82c2e75a5b4/cloud-controller-manager/do/resources.go#L133:21)) by including addresses. I also happen to be experimenting with an idea currently that may allow us to remove part of the caching layer. To my understanding, it should return the ability to use private and public IP addresses as a convenient side effect.

I expect to know if my idea is leading to something by the end of the week, so let me get back to you by then. Just to be clear, this is a bug and we are going to fix it -- it's only a matter of whether we do it by reverting part of the cache or extending on the cache. (Clearly, I prefer the former if that route proves to be viable because a world with less caching is an easier one to navigate through.)

**Comment by timoreimann** [comment]
It still needs explicit testing, but #223 should fix this bug.

**Comment by timoreimann** [comment]
I was able to successfully bootstrap a cluster using private IP addresses as node names.

We also have a unit test now to cover the relevant code.

A new CCM release will be cut next week shipping the fixes.

**Comment by timoreimann** [comment]
[v0.1.15 has been released](https://github.com/digitalocean/digitalocean-cloud-controller-manager/releases/tag/v0.1.15).
