### ISSUE TITLE
wrong apiversion on kubernetes version v1.16

### ISSUE THREAD

**Issue by smilelikeshit** [digitalocean/digitalocean-cloud-controller-manager#288]
hi, im already new installed cluster k8s on digitalocean droplet. but whem im a
pply on releases/v0.1.20.yml got error like below.

serviceaccount/cloud-controller-manager created
clusterrole.rbac.authorization.k8s.io/system:cloud-controller-manager created
clusterrolebinding.rbac.authorization.k8s.io/system:cloud-controller-manager created
error: unable to recognize "v0.1.20.yml": no matches for kind "Deployment" in version "extensions/v1beta1"

thank you

**Comment by timoreimann** [comment]
Hi 👋

This is because the `extensions/v1beta*` API groups stopped being served in Kubernetes 1.16. The latest master of the CCM project already moved all example manifests to `apps/v1`. We're going to release CCM v0.1.21 next week and along with that, provide the proper API version (and the Kubernetes dependencies updated to 1.16 as well just in case).

In the meantime, you can change the API version in the v0.1.20 manifest yourself, and things should work then.

Let's keep the issue open until the next release is out.

**Comment by smilelikeshit** [comment]
hi @timoreimann  . i'll try update script yaml using apiVersion: apps/v1

spec:
  replicas: 1
  selector:
    matchLabels:
     app: digitalocean-cloud-controller-manager


just add selector. and running well on kubernetes version v1.16.2
thank you
