### ISSUE TITLE
[do-loadbalancer-name] doesn't seem to be working

### ISSUE THREAD

**Issue by IljaDaderko** [digitalocean/digitalocean-cloud-controller-manager#322]
Adding following lines in yaml config doesn't seem to be setting load balancer name correctly

```yaml
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "development-graphql-lb"
```

Load balancer is still created with random name `a[uid]`

**Comment by timoreimann** [comment]
@IljaDaderko the feature to rename LBs was only added in our latest CCM release v0.1.24. If you use DigitalOcean's managed Kubernetes service, you should be able to benefit from all features and bug-fixes shipping with CCM v0.1.24 in the next batch of DOKS releases. For self-managed clusters, you should make sure that you run this very CCM version.

**Comment by IljaDaderko** [comment]
Ah, I see. I am indeed on managed one

**Comment by timoreimann** [comment]
@IljaDaderko FYI, we just released a batch of DOKS versions that ship the feature you were looking for. 🎉 See [our change log](https://www.digitalocean.com/docs/kubernetes/changelog/) for details.

**Comment by aholbreich** [comment]
@timoreimann  i would like to reuse loadbalancer with severla services... My plan was to add the same name... 
`service.beta.kubernetes.io/do-loadbalancer-name: "lb1"`

however it worked in a way:
1) the existing LB was renamed to lb1
2) the second service has initiated the creation of second LB with generated name. And this second loadbalancer is completely in crazzy status. I can't even delete that.

Expected behaviour.:
- 2) if second, third and fourt service is createdd with the name of existing LB, then it's reused and only forwaridn rule is appended

**Comment by timoreimann** [comment]
@aholbreich would you mind creating a new issue with more details on what you'd like to do, what you tried, and what ended up happening? Thanks!

**Comment by aholbreich** [comment]
@timoreimann - i've just learned i cannot configure several LB  listeners for one and same port (443) differ only by domain. So if 443 is already has one rule, no second is possible even if another certificate is given. This seem to be limitation of DO LB, the UI don't let me do this.  The docu was not precise about this.  So looks like it's not limitation of this project, so no need for new issue here. Sorry for disturbance.
