### ISSUE TITLE
Provide mechanism to create load balancer in specific project

### ISSUE THREAD

**Issue by Carrdinal** [digitalocean/digitalocean-cloud-controller-manager#370]
I have all of my digitalocean resources assigned to project I am working on except for my load-balancer which is provisioned by DOKS into my default project.

I know I am able to move it after creation but it would be far more convenient if there was an annotation I could set on the service to assign the project.

**Comment by timoreimann** [comment]
Hey @Carrdinal 👋 

we are currently working on projects supports for DOKS, which will include putting all resources associated with a cluster in the same project as the cluster. That way, you wouldn't even need to set an annotation on the Service.

Let me know if that'd fit your needs, thanks.

**Comment by Carrdinal** [comment]
That sounds like a perfect solution! Is there any way I can track this or contribute?

**Comment by timoreimann** [comment]
@Carrdinal contribution won't be possible since the work is purely internal / backend-related. I did just create digitalocean/DOKS#23 to track the effort -- feel free to subscribe, I'll make sure to update the issue as we move forward.

Closing the issue here so that we can move any follow-up discussion to the new ticket. Thanks!
